import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em destaque
        </h1>

        <Link href='/search'> Go to search </Link>

        <ul>
          {list.map( item => (
            <li className={styles.listMovies}> 
              <a href={`/movie/${item.id}`}>
                <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width='150'/>
                <span> {item.title} </span> 
              </a>
            </li>
          ))}
        </ul>
        
      </main>

    </div>
  )
}

export async function getServerSideProps(){

  const response = await fetch('http://localhost:3000/api/trending')
  const data = await response.json();

  return {
    props: {
      list: data.list
    }
  }

}