import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Search.module.css'
import {index} from './index'

export default function Search() {

  const [search, setSearch] = useState('');
  const [movieResult, setMovieResult] = useState([]);

  const searchMovie = async () => {

    if(search !== ''){
      const response = await fetch(`http://localhost:3000/api/movies?q=${search}`)
      const data = await response.json();

      setMovieResult(data.list);
      showMovie(search);
    }
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title> Search a movie </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1> Search a movie </h1>

        <div className={styles.wrapperInput}>
          <input placeholder='Type a movie title' 
                onChange={ e => setSearch(e.target.value)} 
                value={search}> 
          </input>
          <button onClick={searchMovie}> Search </button>
        </div>

      </main>
    </div>
  )
}