import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({list}) {

  const [search, setSearch] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title> Search a movie </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> Search a movie </h1>
        <input placeholder='Type a movie title' 
               onChange={ e => setSearch(e.target.value)} 
               value={search}> 
        </input>

      </main>
    </div>
  )
}